# Generated by Django 5.1.4 on 2025-03-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'following'], name='network_fol_followe_15a782_idx'),
        ),
    ]
