# Generated by Django 5.1.4 on 2025-04-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_network_fol_followe_15a782_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_avatar.png', null=True, upload_to='profile_images/'),
        ),
    ]
