# Generated by Django 5.1.4 on 2025-04-27 04:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_avatar_rwyl0z', max_length=255, null=True, verbose_name='image'),
        ),
    ]
