# Generated by Django 5.1.4 on 2025-05-05 05:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_cloud',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_avatar_rwyl0z', max_length=255, null=True, verbose_name='image'),
        ),
    ]
